"""
SPDC SIMULATION - TWO-MODE SQUEEZED VACUUM (ANALYTICAL)
This is the exact quantum state generated by SPDC.
"""

import numpy as np
import matplotlib.pyplot as plt

print("="*70)
print("SPDC SIMULATION - TWO-MODE SQUEEZED VACUUM")
print("="*70)

# ============================================================================
# PARAMETERS
# ============================================================================

r = 1.0  # Squeezing parameter (0 = no squeezing, >0 = entanglement)
theta = 0.0
n_max = 10

print(f"\nParameters:")
print(f"  Squeezing parameter r = {r}")
print(f"  Mean photons per mode = {np.sinh(r)**2:.4f}")

# ============================================================================
# TWO-MODE SQUEEZED VACUUM STATE
# ============================================================================

def two_mode_squeezed_state(n_max, r):
    coeffs = []
    for n in range(0, n_max + 1):
        coeff = np.sqrt(np.tanh(r)**(2*n)) / np.cosh(r)
        coeffs.append(coeff)
    return coeffs

coeffs = two_mode_squeezed_state(n_max, r)
norm = sum([abs(c)**2 for c in coeffs])
print(f"  Norm (should be 1): {norm:.6f}")

# ============================================================================
# PHOTON NUMBER DISTRIBUTION
# ============================================================================

print("\n" + "="*60)
print("PHOTON NUMBER DISTRIBUTION")
print("="*60)

probs = [np.tanh(r)**(2*n) / np.cosh(r)**2 for n in range(0, n_max + 1)]

print(f"\n  n     P(n)")
print(f"  {'-'*20}")
for n in range(min(8, n_max + 1)):
    print(f"  {n}     {probs[n]:.6f}")

# ============================================================================
# ENTANGLEMENT MEASURES
# ============================================================================

print("\n" + "="*60)
print("ENTANGLEMENT MEASURES")
print("="*60)

entropy = np.cosh(r)**2 * np.log(np.cosh(r)**2) - np.sinh(r)**2 * np.log(np.sinh(r)**2)
entropy_bits = entropy / np.log(2)

print(f"\n  Squeezing parameter r = {r}")
print(f"  Mean photons <n> = {np.sinh(r)**2:.4f}")
print(f"  Entanglement entropy = {entropy:.4f} nats")
print(f"  Entanglement entropy = {entropy_bits:.4f} bits")
print(f"  → State {'IS ENTANGLED' if r > 0 else 'IS NOT ENTANGLED'}")

# ============================================================================
# COINCIDENCE RATE
# ============================================================================

print("\n" + "="*60)
print("EXPERIMENTAL PREDICTIONS")
print("="*60)

pump_powers_mW = np.array([20, 50, 100, 150, 200, 250])
mean_photons = np.sinh(r)**2
coincidence_rates = mean_photons * (pump_powers_mW / 100) * 1e6

print(f"\n  Mean pairs per pulse: {mean_photons:.4f}")
print(f"\n  Predicted coincidence rates:")
for p, rate in zip(pump_powers_mW, coincidence_rates):
    print(f"    {p:3d} mW: {rate:.1f} Hz")

# ============================================================================
# PLOTS
# ============================================================================

print("\nGenerating plots...")

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

n_vals = np.arange(0, n_max + 1)
axes[0, 0].bar(n_vals, probs[:n_max+1], color='blue', alpha=0.7, edgecolor='black')
axes[0, 0].set_xlabel('Photon Number n')
axes[0, 0].set_ylabel('Probability P(n)')
axes[0, 0].set_title(f'(a) Photon Number Distribution (r = {r})')
axes[0, 0].grid(True, alpha=0.3)

r_vals = np.linspace(0, 2, 50)
entropy_vals = []
for r_val in r_vals:
    if r_val > 0:
        ent = np.cosh(r_val)**2 * np.log(np.cosh(r_val)**2) - np.sinh(r_val)**2 * np.log(np.sinh(r_val)**2)
    else:
        ent = 0
    entropy_vals.append(ent)

axes[0, 1].plot(r_vals, entropy_vals, 'b-', linewidth=2)
axes[0, 1].set_xlabel('Squeezing parameter r')
axes[0, 1].set_ylabel('Entanglement Entropy (nats)')
axes[0, 1].set_title('(b) Entanglement vs Squeezing')
axes[0, 1].grid(True, alpha=0.3)
axes[0, 1].axvline(x=r, color='r', linestyle='--', label=f'Your r = {r}')
axes[0, 1].legend()

mean_photons_vals = np.sinh(r_vals)**2
axes[1, 0].plot(r_vals, mean_photons_vals, 'b-', linewidth=2)
axes[1, 0].set_xlabel('Squeezing parameter r')
axes[1, 0].set_ylabel('Mean Photons <n>')
axes[1, 0].set_title('(c) Mean Photons vs Squeezing')
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].axvline(x=r, color='r', linestyle='--', label=f'Your r = {r}')
axes[1, 0].legend()

axes[1, 1].plot(pump_powers_mW, coincidence_rates, 'bo-', linewidth=2, markersize=8)
axes[1, 1].set_xlabel('Pump Power (mW)')
axes[1, 1].set_ylabel('Coincidence Rate (Hz)')
axes[1, 1].set_title('(d) Predicted Coincidence Rate')
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('spdc_analytical_entanglement.png', dpi=300)
plt.savefig('spdc_analytical_entanglement.pdf')
plt.close()

print("✓ Saved: spdc_analytical_entanglement.png/pdf")

# ============================================================================
# SUMMARY
# ============================================================================

print("\n" + "="*70)
print("SIMULATION COMPLETE")
print("="*70)
print(f"""
KEY RESULTS:
-----------
Squeezing parameter r = {r}
Mean photons per mode = {np.sinh(r)**2:.4f}

ENTANGLEMENT:
- For r > 0, the state is ENTANGLED
- Entanglement entropy = {entropy:.4f} nats

The two-mode squeezed vacuum is the exact quantum state generated by SPDC.
This analytical solution is exact and does not require numerical simulation.
""")
print("="*70)